pool:
  name: Azure Pipelines
  demands: maven

steps:
- task: Maven@4
  displayName: 'Maven pom.xml'

- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'springboot-demo-poc'
    azureContainerRegistry: '{"loginServer":"myacrrepo012.azurecr.io", "id" : "/subscriptions/2d16c185-a0af-4f23-a0fd-05a30b6c7195/resourceGroups/springboot-demo/providers/Microsoft.ContainerRegistry/registries/myacrrepo012"}'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'springboot-app-demo'
    azureContainerRegistry: '{"loginServer":"myacrrepo012.azurecr.io", "id" : "/subscriptions/2d16c185-a0af-4f23-a0fd-05a30b6c7195/resourceGroups/springboot-demo/providers/Microsoft.ContainerRegistry/registries/myacrrepo012"}'
    action: 'Push an image'
    includeLatestTag: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: 'aks-deploy-from-acr.yaml'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
